# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  ignore:
      - dependency-name: "chalk"
        # ignore all updates for version 4 and 5
        versions: ["4.x", "5.x"]
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
