installStatePath: "./.yarn/install-state.gz"

cacheFolder: "./.yarn/cache"

enableGlobalCache: false

patchFolder: "./.yarn/patches"

checksumBehavior: update

cloneConcurrency: 1

compressionLevel: mixed

enableImmutableInstalls: false

enableTransparentWorkspaces: true

enableInlineBuilds: true

enableScripts: true

networkConcurrency: 1

nmHoistingLimits: workspaces

nmSelfReferences: true

nmMode: "hardlinks-local"

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.5.0.cjs
