cacheFolder: ./.yarn/cache

checksumBehavior: update

cloneConcurrency: 1

compressionLevel: mixed

enableGlobalCache: false

enableImmutableInstalls: false

enableInlineBuilds: true

enableScripts: true

enableTransparentWorkspaces: true

installStatePath: ./.yarn/install-state.gz

networkConcurrency: 1

nmHoistingLimits: workspaces

nmMode: hardlinks-local

nmSelfReferences: true

nodeLinker: node-modules

patchFolder: ./.yarn/patches

yarnPath: .yarn/releases/yarn-4.9.2.cjs
