cacheFolder: ./.yarn/cache

checksumBehavior: update

cloneConcurrency: 1

compressionLevel: mixed

enableGlobalCache: false

enableImmutableInstalls: false

enableInlineBuilds: true

enableScripts: true

networkConcurrency: 1

nmHoistingLimits: workspaces

nodeLinker: node-modules

patchFolder: ./.yarn/patches

yarnPath: .yarn/releases/yarn-4.5.0.cjs
