cacheFolder: './.yarn/cache'
patchFolder: './.yarn/patches'

checksumBehavior: update

cloneConcurrency: 1

enableGlobalCache: false

enableImmutableInstalls: false

enableInlineBuilds: true

enableScripts: true

networkConcurrency: 1

nmHoistingLimits: workspaces

nodeLinker: node-modules

packageExtensions:
  sbg-api@*:
    dependencies:
      hexo: 'https://github.com/dimaslanjaka/hexo/raw/06b3b7ee/releases/hexo.tgz'
  hexo@*:
    dependencies:
      hexo-log: 'https://github.com/dimaslanjaka/hexo/raw/06b3b7ee/releases/hexo-log.tgz'
      hexo-cli: 'https://github.com/dimaslanjaka/hexo/raw/06b3b7ee/releases/hexo-cli.tgz'
      hexo-util: 'https://github.com/dimaslanjaka/hexo/raw/06b3b7ee/releases/hexo-util.tgz'
      warehouse: 'https://github.com/dimaslanjaka/hexo/raw/06b3b7ee/releases/warehouse.tgz'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'

yarnPath: .yarn/releases/yarn-3.5.1.cjs
