export const greekLetters = {
  alpha: 'α',
  ALPHA: 'Α',
  beta: 'β',
  BETA: 'Β',
  gamma: 'γ',
  GAMMA: 'Γ',
  delta: 'δ',
  DELTA: 'Δ',
  epsilon: 'ε',
  EPSILON: 'Ε',
  zeta: 'ζ',
  ZETA: 'Ζ',
  eta: 'η',
  ETA: 'Η',
  theta: 'θ',
  THETA: 'Θ',
  iota: 'ι',
  IOTA: 'Ι',
  kappa: 'κ',
  KAPPA: 'Κ',
  lambda: 'λ',
  LAMBDA: 'Λ',
  mu: 'μ',
  MU: 'Μ',
  nu: 'ν',
  NU: 'Ν',
  xi: 'ξ',
  XI: 'Ξ',
  omicron: 'ο',
  OMICRON: 'Ο',
  pi: 'π',
  PI: 'Π',
  rho: 'ρ',
  RHO: 'Ρ',

  // Sigma has two lowercase forms (σ, ς)
  sigma: 'σ',
  SIGMA: 'Σ',
  sigmaFinal: 'ς',

  tau: 'τ',
  TAU: 'Τ',
  upsilon: 'υ',
  UPSILON: 'Υ',
  phi: 'φ',
  PHI: 'Φ',
  chi: 'χ',
  CHI: 'Χ',
  psi: 'ψ',
  PSI: 'Ψ',
  omega: 'ω', // Lowercase omega: \u03C9
  OMEGA: 'Ω' // Uppercase Omega: \u03A9
};
