name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn build
        env:
          NEXT_PUBLIC_BASE_PATH: /paraphrasing-tool
      - run: yarn run export
        env:
          NEXT_PUBLIC_BASE_PATH: /paraphrasing-tool
      - run: touch ./out/.nojekyll
      - uses: JamesIves/github-pages-deploy-action@3.5.9
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: out # The folder the action should deploy.
