// git submodule update -i -r
const { spawn } = require('child_process');
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');

if (fs.existsSync(path.join(root, '.git'))) {
  console.log('installing from github repository');
  spawn('git', ['pull', '--all'], {
    cwd: root,
    shell: true,
    stdio: 'inherit'
  });
  spawn('git', ['submodule', 'update', '-i', '-r'], {
    cwd: root,
    shell: true,
    stdio: 'inherit'
  });
} else {
  console.log('installing from npm registry, skipping preinstall');
}

// mock data

[
  'src/types/_config_project.json',
  'src/types/_config_theme.json',
  'src/types/_config_hashes.json',
  'src/gulp/server/routes.json'
].forEach((jsonAutoGeneratedFile) => {
  const src = path.join(__dirname, '..', jsonAutoGeneratedFile);
  const dist = path.join(__dirname, '../dist', jsonAutoGeneratedFile);
  if (!fs.existsSync(dist)) {
    tryCatch(() => {
      fs.mkdirSync(path.dirname(dist), { recursive: true });
      fs.writeFileSync(dist, '{}');
    });
  }
  if (!fs.existsSync(src)) {
    tryCatch(() => {
      fs.mkdirSync(path.dirname(src), { recursive: true });
      fs.writeFileSync(src, '{}');
    });
  }
});

function tryCatch(fn) {
  if (typeof fn === 'function') {
    try {
      fn();
    } catch {
      //
    }
  }
}
