# default config static-blog-generator
# Generator options
generator:
  ## Enable caching (gulp cache, post cache)
  cache: true

# Deployment options
deploy:
  type: "git"
  repo: ""
  branch: "gh-pages"
  user: ""
  email: ""
  message: "{{ now('YYYY-MM-DD HH:mm:ss') }}"

## Categories and Tags
tags:
  lowercase: true # turn all terms to be lowercase
  ## Assign existing tag to new tag
  assign:
  ### Replace Tag to New Tag
  mapper:
    JS: Javascript
    TS: Typescript

categories:
  lowercase: true # turn all terms to be lowercase
  ## Assign existing category to new category
  ### Auto add category on existing category
  assign:
    TS: Programming
    JS: Programming
    Typescript: Programming
    Javascript: Programming
    GitHub: Programming
  ### Replace Category to New Category
  mapper:
    JS: Javascript
    TS: Typescript