#!/usr/bin/env sh

# make cygwin bin as priority
export PATH="node_modules/.bin:bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:$PATH"

case `uname` in
  *CYGWIN*) (set -o igncr) 2>/dev/null && set -o igncr;; # cygwin encoding fix
esac

# Exit silently if git-lfs is not installed
command -v git-lfs >/dev/null 2>&1 || exit 0

# Only run if LFS is initialized/configured
if git config --local --get-regexp '^filter\.lfs\.' >/dev/null 2>&1; then
    git lfs post-commit "$@"
fi
