#!/usr/bin/env sh

set -e

ROOT_GIT=$(git rev-parse --show-toplevel)

cp "${ROOT_GIT}/readme.md" "${ROOT_GIT}/packages/static-blog-generator/readme.md" 2>/dev/null
git add "${ROOT_GIT}/packages/static-blog-generator/readme.md" 2>/dev/null

npx lint-staged

# Exit silently if git-lfs is not installed
command -v git-lfs >/dev/null 2>&1 || exit 0

# Only run if LFS is configured in this repo
if git config --local --get-regexp '^filter\.lfs\.' >/dev/null 2>&1; then
    git lfs pre-push "$@"
fi
