name: Beta Builder

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      ACCESS_TOKEN:
        required: true

jobs:
  build:
    env:
      NODE_OPTIONS: '--max-old-space-size=8192'
      YARN_ENABLE_IMMUTABLE_INSTALLS: false
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      node_version: 18.x

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: dimaslanjaka/static-blog-generator
          ref: master
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: update submodules
        shell: bash
        run: |
          echo "init submodules"
          git submodule init
          git submodule foreach "git submodule init"
          echo "sync submodules"
          git submodule sync
          git submodule foreach "git submodule sync"
          echo "update submodules"
          mkdir -p bin >/dev/null 2>&1
          curl -L https://github.com/dimaslanjaka/bin/raw/master/bin/submodule-install > bin/submodule-install
          rm -rf .git/modules
          bash ./bin/submodule-install
          echo "disable githooks warning"
          git config advice.ignoredHook false

      - name: Set EOL git configs
        continue-on-error: true
        run: |
          git config core.eol lf
          git config core.autocrlf input
          git checkout-index --force --all

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache-key: ${{ runner.os }}-${{ env.node_version }}
          cache-paths: |
            ${{ steps.set-env.outputs.CACHE_NPM }}
            ${{ steps.set-env.outputs.CACHE_YARN }}
            ./packages/sbg-server/src/public
            **/.yarn
            ./yarn.lock
            **/dist

      - name: Set env
        id: set-env
        shell: bash
        run: |
          echo "${HOME}/.local/bin" >> $GITHUB_PATH
          echo "${GITHUB_WORKSPACE}/bin" >> $GITHUB_PATH
          echo "${GITHUB_WORKSPACE}/node_modules/.bin" >> $GITHUB_PATH
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_OUTPUT
          echo "GITHUB_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          echo "GITHUB_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
          echo "GITHUB_COMMIT_URL=https://github.com/${{github.repository}}/commit/$(echo $GITHUB_SHA)" >> $GITHUB_ENV
          echo "GITHUB_COMMIT_URL=https://github.com/${{github.repository}}/commit/$(echo $GITHUB_SHA)" >> $GITHUB_OUTPUT
          echo "GITHUB_RUNNER_URL=https://github.com/${{github.repository}}/commit/${{github.sha}}/checks/${{github.run_id}}" >> $GITHUB_ENV
          echo "GITHUB_RUNNER_URL=https://github.com/${{github.repository}}/commit/${{github.sha}}/checks/${{github.run_id}}" >> $GITHUB_OUTPUT
          echo "CACHE_NPM=$(npm config get cache)" >> $GITHUB_ENV
          echo "CACHE_NPM=$(npm config get cache)" >> $GITHUB_OUTPUT
          YARN_CURRENT=$(yarn -v)
          YARN_BERRY=3.2.1
          if [[ "ok" == "$(echo | awk "(${YARN_CURRENT} > ${YARN_BERRY}) { print \"ok\"; }")" ]]; then
            echo "CACHE_YARN=$(yarn config get cacheFolder)" >> $GITHUB_ENV
            echo "CACHE_YARN=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
          else
            echo "CACHE_YARN=$(yarn cache dir)" >> $GITHUB_ENV
            echo "CACHE_YARN=$(yarn cache dir)" >> $GITHUB_OUTPUT
          fi
          echo "architecture=$(getconf LONG_BIT)" >> $GITHUB_ENV
          if [ -f "package-lock.json" ]; then
              echo "PACKAGE-MANAGER=npm" >> $GITHUB_OUTPUT
              echo "PACKAGE-MANAGER=npm" >> $GITHUB_ENV
          else
              echo "PACKAGE-MANAGER=yarn" >> $GITHUB_OUTPUT
              echo "PACKAGE-MANAGER=yarn" >> $GITHUB_ENV
          fi
          unameOut="$(uname -s)"
          case "${unameOut}" in
              Linux*)     machine=linux;;
              Darwin*)    machine=mac;;
              CYGWIN*)    machine=cygwin;;
              MINGW*)     machine=mingw;;
              *)          machine="unknown:${unameOut}"
          esac
          echo "machine=$machine" >> $GITHUB_OUTPUT
          echo "machine=$machine" >> $GITHUB_ENV

      - uses: actions/cache/restore@v3
        name: restore caches
        with:
          path: ${{ env.cache-paths }}
          key: ${{ env.cache-key }}

      - name: Install Global Packages
        run: |
          corepack enable
          yarn dlx npm i -g npm
          npm i -g typescript ts-node gulp-cli hexo-cli webpack-cli npm-run-all depcheck lerna husky

      - run: yarn install
        name: installing
        continue-on-error: true
        id: install
        shell: bash
      - name: clean install
        if: steps.install.outcome == 'failure'
        shell: bash
        run: |
          yarn cache clean --all
          find . -name 'node_modules' -type d -prune -exec rm -rf '{}' +
          truncate -s 0 yarn.lock
          YARN_CHECKSUM_BEHAVIOR=update yarn install
      - run: yarn run build
        shell: bash
        name: building
      - run: yarn run pack
        shell: bash
        name: packing
      - uses: actions/upload-artifact@v3
        name: upload build result
        timeout-minutes: 10
        with:
          if-no-files-found: 'warn'
          name: dist-artifact
          path: |
            ./yarn.lock
            ./packages/**/dist
            ./packages/**/release*/readme.md
            ./packages/**/release*/*.tgz
            ./packages/sbg-server/src/public
            !**/node_modules/**
            !**/tmp/**
      - uses: actions/cache/save@v3
        name: save caches
        with:
          path: ${{ env.cache-paths }}
          key: ${{ env.cache-key }}
