name: Build

on:
  push:
    branches: [ dev ]

# cancel previous workflows, run only one workflow
#concurrency:
#  group: build-${{ github.event.push.number || github.event.pull_request.number || github.ref }}
#  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Asia/Jakarta"
        timezoneMacos: "Asia/Jakarta"
        timezoneWindows: "Western Indonesia Time"
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        token: "${{ secrets.GITHUB_TOKEN }}"
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'

    - name: Install dependencies
      run: |
        npm i -g gulp-cli typescript npm ts-node
        yarn install --check-files
        yarn add git+https://github.com/dimaslanjaka/persistent-cache.git#improve2
        yarn add git+https://github.com/dimaslanjaka/hexo-post-parser.git#main
        yarn add git+https://github.com/dimaslanjaka/google-news-sitemap.git#main
        yarn add git+https://github.com/dimaslanjaka/safelink.git#main
        yarn remove gulp node-sass lodash.deburr
        yarn add gulp node-sass lodash.deburr
        git add package.json
        git commit -m "fix module resolutions"

    - name: Build
      run: yarn build

    - name: deploy
      run: |
        git config user.email "dimaslanjaka@gmail.com"
        git config user.name "dimaslanjaka"
        git add dist
        git commit -m "build $(date)"
        git push

#    - name: Re-deploy 🚀
#      uses: JamesIves/github-pages-deploy-action@v4.3.0
#      with:
#        branch: main # The branch the action should deploy to.
#        folder: . # The folder the action should deploy.
#        force: false # merge instead delete old files
#        token: "${{ secrets.GITHUB_TOKEN }}"
