name: Clean Caches

on:
  push:
    branches: ['master', 'beta']
    paths:
      - '**/package-lock.json'
      - '**/yarn.lock'
      - '**/_config.yml'
  pull_request:
    paths:
      - '**/package-lock.json'
      - '**/yarn.lock'
      - '**/_config.yml'
  workflow_dispatch:

# run single job
concurrency:
  group: clean-caches
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest

    name: Cache Cleaner
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN || secrets.GITHUB_TOKEN }}
      # https://github.com/actions/cache/blob/main/tips-and-workarounds.md#force-deletion-of-caches-overriding-default-cache-eviction-policy
      - name: Cleanup caches
        shell: bash
        run: |
          npx -y clean-github-actions-caches
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN || secrets.GITHUB_TOKEN }}
