name: Docs Build

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Dev Build"]
    types:
      - completed

# cancel previous workflows, run only one workflow
#concurrency:
#  group: build-${{ github.event.push.number || github.event.pull_request.number || github.ref }}
#  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Asia/Jakarta"
        timezoneMacos: "Asia/Jakarta"
        timezoneWindows: "Western Indonesia Time"
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        token: "${{ secrets.GITHUB_TOKEN }}"
    - uses: actions/setup-node@v3
      with:
        node-version: '16'

    # https://stackoverflow.com/a/61699863/6404439
    # ${{ steps.vars.outputs.branch }}
    # ${{ steps.vars.outputs.hash }}
    - name: Declare some variables
      id: vars
      shell: bash
      run: |
        echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        echo "::set-output name=hash::$(git rev-parse --short HEAD)"
        echo "::set-output name=yarn::$(yarn cache dir)"
        echo "::set-output name=npm::$(npm config get cache)"
    - uses: actions/cache@v3
      with:
        path: |
          ${{ steps.vars.outputs.npm }}
          ./tmp
          ./node_modules
          ./.deploy_*
        key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
    - name: Resolve git user
      continue-on-error: true
      run: |
        cdir="$PWD"
        git checkout dev
        git config user.email "dimaslanjaka@gmail.com"
        git config user.name "dimaslanjaka"
        git fetch --all
        git pull --all
        git submodule update -i -r
        git submodule foreach git submodule update -i -r

    - run: npm i -g gulp-cli typescript npm ts-node npm yarn
    - run: npm ci
    - run: gulp sbg:docs test:generate:index --nocache --verbose --dev
