name: Test

on:
  push:
    branches: [ "beta" ]
  workflow_dispatch:

# run single job
concurrency:
  group: test
  cancel-in-progress: true

jobs:
  cli:
    strategy:
      fail-fast: true
    env:
      NODE_OPTIONS: "--max-old-space-size=8192"

    runs-on: ubuntu-latest

    name: "Test Using CLI"
    steps:
      - uses: actions/checkout@v3
        with:
          repository: dimaslanjaka/static-blog-generator
          ref: beta
          token: ${{ secrets.ACCESS_TOKEN }}
      - run: sh scripts/install-submodules.sh
        name: clone submodules
      - name: Set env
        id: set-env
        shell: bash
        run: |
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
          echo "GITHUB_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          echo "GITHUB_COMMIT_URL=https://github.com/${{github.repository}}/commit/$(echo $GITHUB_SHA)" >> $GITHUB_ENV
          echo "GITHUB_RUNNER_URL=https://github.com/${{github.repository}}/commit/${{github.sha}}/checks/${{github.run_id}}" >> $GITHUB_ENV
          echo "CACHE_NPM=$(npm config get cache)" >> $GITHUB_ENV
          echo "CACHE_YARN=$(yarn cache dir)" >> $GITHUB_ENV
          echo "CACHE_YARN2=$(yarn config get cacheFolder)" >> $GITHUB_ENV
          echo "cache-npm=$(npm config get cache)" >> $GITHUB_OUTPUT
          echo "cache-yarn=$(yarn cache dir)" >> $GITHUB_OUTPUT
          echo "cache-yarn2=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - name: Get env
        run: |
          echo "branch      : ${{ env.GITHUB_BRANCH }}"
          echo "commit msg  : ${{ github.event.head_commit.message }}"
          echo "commit hash : ${{ env.GITHUB_SHA_SHORT }}"
          echo "commit url  : ${{ env.GITHUB_COMMIT_URL }}"
          echo "runner url  : ${{ env.GITHUB_RUNNER_URL }}"
          echo "cache npm   : ${{ env.CACHE_NPM }}"
          echo "cache yarn  : ${{ env.CACHE_YARN }}"
          echo "cache yarn2 : ${{ env.CACHE_YARN2 }}"

      - name: Set EOL git configs
        continue-on-error: true
        run: |
          git config core.eol lf
          git config core.autocrlf input
          git checkout-index --force --all

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          token: ${{ secrets.GITHUB_TOKEN }}
          architecture: x64
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Enable corepack
        run: corepack enable

      - uses: actions/cache@v3 # pat-s/always-upload-cache@v3.0.11
        id: cache
        name: get caches
        with:
          path: |
            ${{ steps.set-env.outputs.cache-npm }}
            ${{ steps.set-env.outputs.cache-yarn }}
            ${{ steps.set-env.outputs.cache-yarn2 }}
            **/packages/**/dist/**
            ./packages/sbg-server/src/public
            **/tmp/**
            **/node_modules/**
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
            ${{ runner.os }}-

      - name: Install Global Packages
        run: npm i -g typescript ts-node gulp-cli hexo-cli webpack-cli npm-run-all depcheck lerna husky

      - run: npm install
        working-directory: test
        id: install
        continue-on-error: true
      - run: npm run update
        if: steps.install.outcome != 'success'
        working-directory: test
      - run: sbg post standalone
        working-directory: test
      - run: sbg post copy
        working-directory: test
      - run: hexo generate
        working-directory: test
