name: Build Beta

on:
  push:
    paths-ignore:
      - '**/dist/**'
      - '**/release*/**'
      - '**/test/**'
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-beta.yml
    secrets: inherit
  test:
    needs: build
    strategy:
      fail-fast: true
    env:
      NODE_OPTIONS: '--max-old-space-size=8192'
      YARN_ENABLE_IMMUTABLE_INSTALLS: false
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: dimaslanjaka/static-blog-generator
          ref: beta
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: 'recursive'
      - name: update submodules
        shell: bash
        run: |
          echo "init submodules"
          git submodule init
          git submodule foreach "git submodule init"
          echo "sync submodules"
          git submodule sync
          git submodule foreach "git submodule sync"
          echo "update submodules"
          mkdir -p bin >/dev/null 2>&1
          curl -L https://github.com/dimaslanjaka/bin/raw/master/bin/submodule-install > bin/submodule-install
          rm -rf .git/modules
          bash ./bin/submodule-install
          echo "disable githooks warning"
          git config advice.ignoredHook false

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - uses: actions/download-artifact@v3
        with:
          name: my-artifact

      - name: Install Global Packages
        run: |
          corepack enable
          yarn dlx npm i -g npm
          npm i -g typescript ts-node gulp-cli hexo-cli webpack-cli npm-run-all depcheck lerna husky

      - run: yarn install
      - run: |
          arr_variable=("sbg-api" "sbg-server" "sbg-utility" "sbg-cli" "static-blog-generator" "instant-indexing")
          for i in "${arr_variable[@]}"
          do
            yarn workspace $i build && yarn workspace $i run pack
          done
        shell: bash
        name: build
      - run: sbg clean all
        working-directory: test
        name: test clean
      - run: sbg post standalone
        working-directory: test
        name: test post standalone
      - run: sbg post copy
        working-directory: test
        name: test post copy
      - run: npx hexo generate
        working-directory: test
        name: test generate site with hexo
      - run: sbg generate feed
        working-directory: test
        name: test generate feed
      - run: sbg generate sitemap
        working-directory: test
        name: test generate sitemap
      - run: sbg deploy copy
        working-directory: test
        name: test copy generated site to deployment directory